/** GENERATED by scripts/stamp-build.mjs. Production stamps this before the one Linux build. */
export const BUILD_INFO = {
  builtAt: null as string | null,
  sha: null as string | null,
} as const;
