import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const target = join(repoRoot, "src/lib/build-info.generated.ts");
const sha = execFileSync("git", ["rev-parse", "HEAD"], {
  cwd: repoRoot,
  encoding: "utf8",
}).trim();

if (!/^[0-9a-f]{40}$/u.test(sha)) {
  throw new Error(`stamp-build: invalid Git SHA ${JSON.stringify(sha)}`);
}

const builtAt = new Date().toISOString();
writeFileSync(
  target,
  `/** GENERATED by scripts/stamp-build.mjs. Production stamps this before the one Linux build. */\nexport const BUILD_INFO = {\n  builtAt: ${JSON.stringify(builtAt)} as string | null,\n  sha: ${JSON.stringify(sha)} as string | null,\n} as const;\n`,
  "utf8"
);
process.stdout.write(`stamp-build: ${sha} (${builtAt}) -> ${target}\n`);
